server:
  port: 8089
spring:
  application:
    name: rabbitmq-consumer
  #rabbitMq
  rabbitmq:
    host: 192.168.88.128
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual